version: "3"
services:

  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wikis
      DB_PASS: wikis
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "8007:3000"
